#!/bin/sh

vagrant_create () {
    set -e

    local OPTS VM_NAME OPT_DISTRIBUTION OPT_FILE OPT_FROM

    OPTS=$(getopt -o "" --long vagrant-file:,vagrant-docker-from: -n "$(basename $0)" -- "$@")
    eval set -- "$OPTS"

    while true; do
	case "$1" in
            --vagrant-file)         OPT_FILE=$1;     shift; shift ;;
            --vagrant-docker-from)  OPT_FROM=$1;     shift; shift ;;

            --) shift; break ;;
            *) echo "Error parsing argument: $1">&2; exit 1 ;;
	esac
    done

    VM_NAME=$1; shift
    OPT_FROM=${OPT_FROM:-ubuntu:precise}; shift

    (
	mkdir -p ~/.travis-run/$VM_NAME
	cp $(dirname $0)/prepare-vm.sh ~/.travis-run/$VM_NAME/

	cat > ~/.travis-run/$VM_NAME/Dockerfile <<EOF
# AUTOMATICALLY GENERATED BY travis-run WILL BE OVERWRITTEN UNCONDITIONALLY!
FROM $OPT_FROM

CMD /usr/sbin/sshd -D

WORKDIR /root
ADD prepare-vm.sh /root/prepare-vm.sh

RUN sh -x /root/prepare-vm.sh vagrant

RUN apt-get update; apt-get install -y openssh-server sudo
RUN adduser vagrant --disabled-password --gecos ""; adduser vagrant sudo
RUN echo 'Defaults    !authenticate' >  /etc/sudoers.d/noauth; chmod 0440 /etc/sudoers.d/noauth
RUN echo "root:vagrant" | chpasswd; echo "vagrant:vagrant" | chpasswd
RUN mkdir /home/vagrant/.ssh; echo 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key' > /home/vagrant/.ssh/authorized_keys; chown -R vagrant:vagrant /home/vagrant/.ssh/; chmod 640 /home/vagrant/.ssh/authorized_keys

RUN mkdir /var/run/sshd
EOF

	docker build -t $VM_NAME ~/.travis-run/$VM_NAME

	mkdir -p .travis-run/$VM_NAME
	cat > .travis-run/$VM_NAME/Dockerfile <<EOF
# AUTOMATICALLY GENERATED BY travis-run WILL BE OVERWRITTEN UNCONDITIONALLY!
FROM $VM_NAME
CMD /usr/sbin/sshd -D
EOF

	cat > .travis-run/$VM_NAME/Vagrantfile <<EOF
# AUTOMATICALLY GENERATED BY travis-run WILL BE OVERWRITTEN UNCONDITIONALLY!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
#  config.vm.synced_folder "../../", "/src"
  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.cmd = ["/usr/sbin/sshd", "-D"]
    d.has_ssh = true
  end
end
EOF
    )
}

vagrant_init () {
    local VM_NAME

    VM_NAME=$1; shift

    if [ ! -d .travis-run/$VM_NAME ]; then
	echo "Can't find vagrant state dir: $PWD/.travis-run/$VM_NAME">&2
	exit 1
    fi

    (
	cd .travis-run/$VM_NAME
	vagrant up --provider=docker
    )
}

vagrant_end () {
    local VM_NAME
    VM_NAME=$1; shift

    if [ ! -d .travis-run/$VM_NAME ]; then
	echo "Can't find vagrant state dir: $PWD/.travis-run/$VM_NAME">&2
	exit 1
    fi

    (
	cd .travis-run/$VM_NAME
	vagrant halt
    )
}

## Usage: vagrant_run VM_NAME COPY? [OPTIONS..] -- COMMAND
vagrant_run () {
    set -e

    local OPTS VM_NAME CPY DIR

    OPTS=$(getopt -o "" -n "$(basename $0)" -- "$@")
    eval set -- "$OPTS"

    while true; do
	case "$1" in
            --) shift; break ;;
            *) echo "Error parsing argument: $1">&2; exit 1 ;;
	esac
    done

    VM_NAME=$1; shift
    CPY=$1; shift

    if [ ! -d .travis-run/$VM_NAME ]; then
	echo "Can't find vagrant state dir: .travis-run/$VM_NAME">&2
	exit 1
    fi

    local dir=$PWD

    # We can ignore most arguments because vagrant already handles that stuff.
    (
	cd .travis-run/$VM_NAME

	if [ x"$CPY" = x"copy" ]; then
	    vagrant ssh -- mkdir -p build/
	    tar -C $dir -c . | vagrant ssh -- tar -C build -x
	    echo
	fi

	vagrant ssh -- "$@"
    )
}
