# AUTOMATICALLY GENERATED BY travis-run WILL BE OVERWRITTEN UNCONDITIONALLY!
## To modify the environment for your builds modify the Dockerfile in
## .travis-run/$VM_NAME in your project directory instead.
FROM %FROM%

WORKDIR /root

ADD language-install.sh /root/
ADD templates /root/

RUN /root/language-install.sh %LANGUAGE% travis
