FROM debian:wheezy

RUN apt-get update && apt-get install -y ruby-dev build-essential git wget
RUN gem install --no-ri --no-rdoc bundler

RUN mkdir -p /root/script/
ADD script/Gemfile       /root/script/
ADD script/Gemfile.lock  /root/script/
RUN cd /root/script && bundle install --system

ADD script/  /root/script/

WORKDIR /root/script
CMD []
ENTRYPOINT ["/root/script/travis-run-script"]
