FROM debian:wheezy

RUN apt-get update && apt-get install -y ruby-dev build-essential git wget
RUN gem install --no-ri --no-rdoc bundler

ADD script/  /root/script/
RUN cd /root/script && bundle install --system

WORKDIR /root/script
CMD []
ENTRYPOINT ["/root/script/travis-run-script"]
