source 'https://rubygems.org'

gem 'travis-build',     :git => 'https://github.com/travis-ci/travis-build'
gem 'travis-core',      :git => 'https://github.com/travis-ci/travis-core'
gem 'travis-support',   :git => 'https://github.com/travis-ci/travis-support'
gem 'travis-sidekiqs',  :git => 'https://github.com/travis-ci/travis-sidekiqs'

gem 'connection_pool'
gem 'factory_girl'
gem 'rake'
